version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.12.1
    - 1.9.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: listen
    versions:
    - 3.5.0
    - 3.5.1
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: skylight
    versions:
    - 5.0.0
  - dependency-name: puma
    versions:
    - 5.2.2
  - dependency-name: omniauth
    versions:
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: jbuilder
    versions:
    - 2.11.2
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: pry-stack_explorer
    versions:
    - 0.6.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@rails/activestorage"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: bootstrap-table
    versions:
    - 1.18.2
  - dependency-name: "@rails/webpacker"
    versions:
    - 5.2.1
