require:
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - node_modules/**/*
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 100
