require:
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - node_modules/**/*
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 12
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/AbcSize:
  Max: 25
