name: Wake up, Heroku

on: 
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://masamune-20200114.herokuapp.com/?from-github-actions
