name: Rubocop Linter Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
    - name: Rubocop Linter
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
